version: "3.8"

services:
  # Base de données PostgreSQL
  db:
    image: postgres:16
    container_name: sama_conai_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: sama_conai_production
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - sama_conai_pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d sama_conai_production"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sama_conai_network

  # Serveur Odoo
  odoo:
    image: odoo:18.0
    container_name: sama_conai_odoo
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PROXY_MODE=True
      - DB_NAME=sama_conai_production
    volumes:
      - sama_conai_odoo_data:/var/lib/odoo
      - ./:/mnt/extra-addons/sama_conai:ro
      - ./logs:/var/log/odoo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8069 || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s
    networks:
      - sama_conai_network

  # Application Mobile Web
  mobile_web:
    build:
      context: ./mobile_app_web
      dockerfile: Dockerfile
    container_name: sama_conai_mobile_web
    depends_on:
      odoo:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - ODOO_URL=http://odoo:8069
      - ODOO_DB=sama_conai_production
      - ODOO_USER=admin
      - ODOO_PASSWORD=admin
      - NODE_ENV=production
    volumes:
      - ./mobile_app_web:/app:ro
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sama_conai_network

  # Nginx Reverse Proxy (optionnel)
  nginx:
    image: nginx:alpine
    container_name: sama_conai_nginx
    depends_on:
      - odoo
      - mobile_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    networks:
      - sama_conai_network

  # Redis pour le cache (optionnel)
  redis:
    image: redis:7-alpine
    container_name: sama_conai_redis
    ports:
      - "6379:6379"
    volumes:
      - sama_conai_redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - sama_conai_network

volumes:
  sama_conai_pg_data:
    driver: local
  sama_conai_odoo_data:
    driver: local
  sama_conai_redis_data:
    driver: local

networks:
  sama_conai_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16