version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PROXY_MODE=True
    volumes:
      - odoo-data:/var/lib/odoo
      - ./:/mnt/extra-addons/sama_conai
    restart: unless-stopped

volumes:
  pg-data:
  odoo-data:
